### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by mrjosshi** [nitin42/react-color-extractor#1]
Access to Image at 'https://s3.ap-south-1.amazonaws.com/workmob-v3/users_posts/154/2227/post_image_1548850277394_2227.png' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. 

this error is showing while using in my code please help

**Comment by nitin42** [comment]
Please use a CORS extension or plugin when requesting the resource.

This component just uses [`node-vibrant`](https://github.com/akfish/node-vibrant) under the hood, so if you can look at their documentation, maybe that could help you with this issue.
